name: VFM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tqdm>=4.64.0
  - opencv
  - jupyter
  - pytest
  - pip
  - pip:
    - pytorch-lightning>=2.0.0
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    - wandb>=0.15.0
    - rich>=13.0.0
    - einops>=0.6.0
    - timm>=0.9.0
    - black>=22.0.0
    - isort>=5.10.0
    - flake8>=5.0.0
    - pytest-cov>=4.0.0
    - pillow>=9.0.0
